### ISSUE TITLE
After 2.0 Beta upgrade I'm not able to create projects. UI doesn't open

### ISSUE THREAD

**Issue by zargyle** [joeferraro/MavensMate-SublimeText#120]
I've been struggling with this error for MavensMate 1...

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- thin (LoadError)

And you recommendation was to wait for MM 2.0.

After installing the new app and plugin the MM plugin has been unresponsive. When I create a new project the UI never pops up, the message at the bottom of the window says "Operating ever so gracefully" really quick then changes to "Operation Complete".

When I try to edit the details of an existing project the console reads...
"Your MavensMate project needs to be upgraded. Opening the upgrade UI."
But the UI never opens.

I have uninstalled both the app and plugin then reinstalled and I am still experiencing this problem.

**Comment by Drobi83** [comment]
@joeferraro Ive had this recently start up since my upgrade to v0.0.10. Here is some debug that you were asking for in the thread.

[MAVENSMATE] failed to send community activity
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: refresh
[MAVENSMATE]: {'params': {'directories': ['D:\\Dropbox\\IDE\\MavensMate\\Workspace\\PC\\miiFormsDev']}, 'context': <MavensMate.mavensmate.RefreshFromServerCommand object at 0x00000013EBE1DEB8>}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\Dave\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" --ui -c SUBLIME_TEXT_3 -o upgrade_project
[MAVENSMATE]: {"workspace": "D:\\Dropbox\\IDE\\MavensMate\\Workspace\\PC", "directories": ["D:\\Dropbox\\IDE\\MavensMate\\Workspace\\PC\\miiFormsDev"], "project_name": "miiFormsDev"}
[MAVENSMATE]: response from mm: {"body": "Unable to retrieve password from the keychain store.", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 76, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.util\", line 557, in generate_ui\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.project\", line 937, in get_creds\nMMException: Unable to retrieve password from the keychain store.\n", "success": false}


[MAVENSMATE] failed to send community activity
