### ISSUE TITLE
Deploy dialog defaults to having metadata pre-selected

### ISSUE THREAD

**Issue by greenstork** [joeferraro/MavensMate-SublimeText#183]
This is dangerous, what if you forget to uncheck metadata prior to a deploy and it's unrelated to the code you are deploying. What if you are working in one org with 8 sandboxes and doing some work in one sandbox and not in another and it's incomplete but gets accidentally selected and deployed to production?

This could all be addressed by a better deploy dialog. Eclipse has a validation step with a complete package (payload metadata) diff dialog. This would be a nice addition to MavensMate.

**Comment by sjurgis** [comment]
I am extremely unhappy about this default.

I already overwrote sandboxes twice just because of this. After first time I became meticulous about it, but it still somehow happened. What is more 'fun' is that somehow old file version got deployed, so still trying to figure out how this happened.

@joeferraro this should be fixed. It's very dangerous and irresponsible to leave it like this.
