### ISSUE TITLE
Autocomplete causes Sublime Text to freeze

### ISSUE THREAD

**Issue by thysmichels** [joeferraro/MavensMate-SublimeText#203]
Sublime V3047
MM V0.35.1

When I open my project and start type auto completion tries to give me suggestions and it then hangs sublime and the wheel of death appears. I have to force quite sublime. Add some documentation to disable autocompletion if this happens.

**Comment by dcrockwell** [comment]
This is happening here with autocompleting anything in a for() loop in javascript.

I didn't notice it until I installed a plugin for jshint linting, but it looks like others have the same issue without this plugin.

**Comment by dcrockwell** [comment]
I've narrowed down the problem in my case to a bug in the jshint binary causing any linter that uses it to freeze sublime with the beach ball of doom.

This isn't really a problem with Sublime, aside from a need for a "cancel" feature on such operations.

**Comment by ruwanthalk** [comment]
This issue is still exist.

I was really frustrated of this when I use mavensmate. 
The issue I faced is I just wanted to type the getBody() of response object. When I type res.b it get stuck several time. This is a great tool. But need to get rid of this kind of annoying issues. Making mm_autocomplete  false is not a solution. Please escalate this issue to make this product really standout.
