### ISSUE TITLE
Create New Project returns 405 "GET not supported"

### ISSUE THREAD

**Issue by sebasao** [joeferraro/MavensMate-SublimeText#416]
Hi,

I'm only having this issue with a Sandbox of an Enterprise Org and it's weird as I'm loging in as Sys Admin so should not be any API permission related issue. Error details are:

>>> request is not ready
[MAVENSMATE UI]: {"id": "ark9y5c3", "status": "pending"}
[MAVENSMATE UI]: >>> got a response body
[MAVENSMATE UI]: {"body": "Error Code 405. Response content: <html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\"/>\n<title>Error 405 GET not supported</title>\n</head>\n<body><h2>HTTP ERROR 405</h2>\n<p>Problem accessing /services/Soap/m/28.0/00D110000007pfM.salesforce.com/services/data/v28.0/tooling/query/. Reason:\n<pre>    GET not supported</pre></p><hr /><i><small>Powered by Jetty://</small></i><br></body>\n</html>", "body_type": "text", "success": false}

The Sbx has a custom domain so the WSDL I got for tooling API has a different endpoint from the one used by MM, don't know if that's something. I don't have any problems connecting to any other Sbx, DE or Prod Orgs.

I'm using MM v3.5.0 on Linux

Any help is much appreciated! Meanwhile I'm using Force.com IDE and I'm not happy :)

Thanks
Seb

**Comment by briandunz** [comment]
Adding to my comment and @derekhansen , our customer orgs are created from TrialForce (with custom domains).  This same org is later provisioned as a production org.  So the domain will look like https://[our company name]-1068--sgsandbox.cs18.cloudforce.com.  I'm specifically getting it in sandboxes from these orgs. Not sure if this helps narrow down the issue.

**Comment by willemmulder** [comment]
We have the same issue. Also with a cloudforce.com domain that started out as a Trial and was upgraded to a full prod org. Looks like a certain URL is built incorrectly? 

    Problem accessing     /services/Soap/m/31.0/00D24000000DLeb.salesforce.com/services/data/v31.0/tooling/query/. Reason:

    GET not supported

**Comment by xiteer** [comment]
Same issue here too. Also same situation. org started as a Trial and was upgrade to full production. This was never a sandbox.
`Error Code 405. Response content:
HTTP ERROR 405
Problem accessing /services/Soap/m/31.0/00Dj0000000KlAQ.salesforce.com/services/data/v31.0/tooling/query/. Reason:

    GET not supported
Powered by Jetty://`

**Comment by SCWells72** [comment]
I don't know if you guys are still seeing this issue, but I'm the developer of another Force.com dev tool and one of my users also encountered a variation on this issue with mine as well as with MM.  After a little research and some help from the user to try things out where the problem was occurring, I've found a solution and wanted to share it here in case it might help.

In MM the problem manifests exactly as described above.  In mine, presumably due to differences in the APIs being called, it manifests as an HTTP 411/Length Required.  I found this discussion:

https://developer.salesforce.com/forums/?id=906F00000009ztsIAA

which led me to disable chunking in my API client.  That resolved the issue!  Note that I did not have to make any changes in whether the client accepts/sends gzip content or not.  I just had to disable chunking.

I have an open question with Salesforce about exactly when/why this might be necessary so I can be more definitive in when I disable chunking and when I don't.  I'll be happy to share any useful responses I get from them as well.

I hope this helps you guys reach a solution!

**Comment by daniel** [comment]
I have the same problem for a developer environment with a custom domain.

```html
<body><h2>HTTP ERROR 405</h2>
<p>Problem accessing /services/Soap/u/31.0. Reason:
<pre>    GET not supported</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>
```

**Comment by renamath** [comment]
I have the same problem.
Solution?

**Comment by renamath** [comment]
updated to version 7 and there was no more trouble
