### ISSUE TITLE
Could not find the mm executable

### ISSUE THREAD

**Issue by timyu000** [joeferraro/MavensMate-SublimeText#513]
Hi,
   When I try to build a new project (MavensMate->Project->New Project)  in Sublime Text 3,the console displays the message:
 "[OPERATION FAILED]: Could not find the mm executable. Please run MavensMate > Install/Update MavensMate API (mm) to install mm to your MavensMate for Sublime Text plugin directory.",and i run (MavensMate > Install/Update MavensMate API (mm)) but it doesn't work.

**Comment by ralphcallaway** [comment]
Hi @timyu000 

in order to troubleshoot this we'll need some additional diagnostic details, can you please enable plugin logging and post the relavant logs? closing for now since we can't do anything without diagnostic info

**Comment by binaryLady** [comment]
I am having the same issue, Windows 7 behind a proxy with settings configured the error is:

[OPERATION FAILED]: Could not find the mm executable. Please run MavensMate > Install/Update MavensMate API (mm) to install mm to your MavensMate for Sublime Text plugin directory.

Nothing happens on update/download

**Comment by ralphcallaway** [comment]
@binaryLady we already closed this one out since we didn't get any logs, see enable plugin logging http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging and please post logs with a new issue (i only noticed this comment since it was in my recent history)

as a workaround, there are several alternative ways to install the "mm" api, see option 3 in http://mavensmate.com/Getting_Started/Users, and the steps beneath "setting up mavensmate for sublime text" in the "settuping up your dev environment" section of http://mavensmate.com/Getting_Started/Developers
