### ISSUE TITLE
Unable to Create a new project

### ISSUE THREAD

**Issue by aragornrok** [joeferraro/MavensMate-SublimeText#515]
Sublime Text version 3.0

API 0.2.4

mavensMate 4.0.2

It says server stopped working or malfunctioning. Restart editor and app.

All folders are created in user directory.

This error messages comes in the ie window for new project.

**Comment by ralphcallaway** [comment]
before we can do much on this you'll need to enable plugin logging and post relevant logs, see http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging

closing this for now since we don't have enough details to troubleshoot, reopen if it's still an issue with the relevant logs, and details on your operating system
