### ISSUE TITLE
Creating a Project from Existing directory Ubuntu

### ISSUE THREAD

**Issue by thegogz** [joeferraro/MavensMate-SublimeText#518]
I'm getting an error when trying to create a project from an existing directory (git project) on my Ubuntu Laptop running 14.04. 

Below is the log

```

--------------------------------------------
---------- NEW OPERATION REQUESTED ---------
--------------------------------------------

new_project_from_existing_directory
Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='new_project_from_existing_directory', quiet=False, respond_with_html=False, ui_switch=True, uid=None, verbose=False)
{'verbose': False, 'args': Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='new_project_from_existing_directory', quiet=False, respond_with_html=False, ui_switch=True, uid=None, verbose=False), 'client': 'SUBLIME_TEXT_3', 'ui': True, u'directory': u'/home/thegogz/Repositories/Salesforce', 'operation': 'new_project_from_existing_directory'}

--------------------------------------------
UI operation requested, attempting to launch MavensMate UI
---------------------
result from command execution
{'body': 'UI Generated Successfully', 'body_type': 'text', 'success': True, 'time': '1.1722140312194824'}
<type 'dict'>
---------------------


---------------------
RESPONDING TO REQUEST
---------------------


{
    "body": "UI Generated Successfully", 
    "body_type": "text", 
    "success": true, 
    "time": "1.1722140312194824"
}
```
Any Ideas?

The browser does open as expected to login but logging in doesn't seem to do anything. 

Creating a new project in the same location works fine.

**Comment by ralphcallaway** [comment]
@thegogz so the log you've posted shows that the new project ui launched but doesn't show an errors during project creation

i've had previous isues with the new project page that failed silently, i used the developer console on the browser new project window and looked for error in the console which there were several

it's been a while since you posted anything to this, are you still having this issue?

**Comment by ralphcallaway** [comment]
@thegogz fyi, as mentioned in #517 if the existing folder is in your workspace, the create project is going to fail, you need to have the existing folder with git repo outside of your workspace initially and then create the project

clearly room for improvement here, we love pull requests!

closing this out since I believe #517 already covers your issues, but please re-open if you feel that's not the case

**Comment by thegogz** [comment]
@ralphcallaway you're right, issue #517 does cover my issue, now that I've read that it makes sense that's what's happening as I use my main repository directory for all projects, this is also where mavensmate uses as its workspace.
