### ISSUE TITLE
Flow metadata never shows the most recent version

### ISSUE THREAD

**Issue by gokubi** [joeferraro/MavensMate-SublimeText#526]
Pulling metadata for flows consistently misses the most recent version. I have a version 28, and MM in Sublime shows 27 as the latest. The metadata for 27 in the file is the correct metadata for 27.

![flow versions in saleforce](https://cloud.githubusercontent.com/assets/288215/5359690/20d98fe2-7f74-11e4-8efe-8e29bfe92652.png)

![flow version in mavensmate in sublime](https://cloud.githubusercontent.com/assets/288215/5359695/27d0fda8-7f74-11e4-91ba-7c8f65b3c231.png)

Mac, Sublime 3065, MM for sublime 4.0.2, sandbox

**Comment by ralphcallaway** [comment]
when you open the edit project window the options for selecting metadata don't update automatically (this is intentional since refreshing that list can be super slow in large orgs)

perhaps you just need to refresh the metadata to see the latest version?

closing for now, please re-open if i'm not understanding your issue correctly

**Comment by abd3721** [comment]
The versioning behavior of Visual Workflow (Flows) and the new Lightning Process Builder is not being handled correctly by MM. Every instance of a Flow or Process has a version. Although in the UI, the version number may not always show, when accessing Flows or Processes as metadata you always need to specify the version number. Version 1 of a Flow is sometimes shown in MM without a version number, which means it won't download to your project and can't be deployed. This screenshot of the Edit Project window shows an attempt to download 2 versions of a Process. 

![screen shot 2015-06-26 at 14 05 10](https://cloud.githubusercontent.com/assets/11654102/8384154/23a94d30-1c0d-11e5-899d-4a53936b64b8.png)

But only the entry with a version number can be downloaded:
![screen shot 2015-06-26 at 14 10 33](https://cloud.githubusercontent.com/assets/11654102/8384163/33984534-1c0d-11e5-96ab-12050098755d.png)

(Process Builder processes are also Flow metadata types and so this problem applies to both)

**Comment by ddeveaux** [comment]
For this issue, MavensMate will not show the version for active Flows. You have to deactivate it and then refresh for this to work and show the latest version. At least prior to MM 6 you could not move Active Flows to other orgs either, had to deactivate, refresh so could see version number, then move. I'm not sure if this is still true with 6 since I always deactivate to ensure using correct version.

In @gokubi example above you see that version 28 is Active hence not showing in list with version #.
