### ISSUE TITLE
Installing MavensMate API (mm) to the user plugin directory

### ISSUE THREAD

**Issue by antocarmel** [joeferraro/MavensMate-SublimeText#533]
When installing MavensMate API (mm),I am getting this message (could not install mm, please generate/check logs and report GitHub issue).I tried many times, but couldn't be successful.Please help me to get through this.
![mavensmate](https://cloud.githubusercontent.com/assets/7296727/5788087/9a38df80-9e48-11e4-8865-c930dabbaeab.JPG)

**Comment by joeferraro** [comment]
Have you checked the Sublime Text console?

**Comment by antocarmel** [comment]
Yes, I have checked it.It had been attempting to download for hours.
![capture 2](https://cloud.githubusercontent.com/assets/7296727/5834805/584d262a-a187-11e4-8e6d-5a31ebed3e1d.JPG)

**Comment by kidtsunami** [comment]
And are you able to download that zip file using a normal browser or curl?




https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip

**Comment by antocarmel** [comment]
Yes,I'm able to download it.

**Comment by ralphcallaway** [comment]
@antocarmel to get this working you can download the file directly and unzip to your <packages>\MavensMate\mm, so that you end up with <packages>\MavensMate\mm\mm.exe

if needed there are several manual installation options, see http://mavensmate.com/Getting_Started/Users and http://mavensmate.com/Getting_Started/Developers

closing for now, re-open if these steps don't get you going
