### ISSUE TITLE
Compile error: JSON dump with no error message

### ISSUE THREAD

**Issue by JenniferSimondsTableau** [joeferraro/MavensMate-SublimeText#534]
When I compile a file, I'm getting an OPERATION FAILED, then a dump of the JSON response from the server. There's no error message, and "problem" = null, although "success" = false and "State" = "Failed".

It started happening yesterday. It happens on some components & pages, but I haven't been able to make it fail for any of our Apex classes.

I can compile the code fine in Salesforce. I tried resetting the metadata container, checked for updates on MM API and SublimeText (both were up to date), and rebuilt the project from the server.

SublimeText is up to date - build 3065.
MavensMate is v4.0.2

The result, after "[OPERATION FAILED]:", is a JSON dump:

```
{
  "attributes": {
    "type": "ContainerAsyncRequest",
    "url": "\/services\/data\/v31.0\/tooling\/sobjects\/ContainerAsyncRequest\/1drg0000000k3dmAAA"
  },
  "State": "Failed",
  "Id": "1drg0000000k3dmAAA",
  "DeployDetails": {
    "runTestResult": null,
    "allComponentMessages": [
      {
        "forPackageManifestFile": false,
        "fullName": "CustomerDeployment_SupportContacts",
        "id": "099g00000000FAkAAM",
        "fileName": "CustomerDeployment_SupportContacts",
        "success": false,
        "columnNumber": -1,
        "knownPackagingProblem": false,
        "problemType": null,
        "created": false,
        "componentType": "ApexComponent",
        "warning": false,
        "problem": null,
        "requiresProductionTestRun": false,
        "changed": false,
        "createdDate": "2015-01-30T18:28:36.663+0000",
        "lineNumber": 1,
        "deleted": false
      }
    ],
    "componentSuccesses": [
      
    ],
    "componentFailures": [
      {
        "forPackageManifestFile": false,
        "fullName": "CustomerDeployment_SupportContacts",
        "id": "099g00000000FAkAAM",
        "fileName": "CustomerDeployment_SupportContacts",
        "success": false,
        "columnNumber": -1,
        "knownPackagingProblem": false,
        "problemType": null,
        "created": false,
        "componentType": "ApexComponent",
        "warning": false,
        "problem": null,
        "requiresProductionTestRun": false,
        "changed": false,
        "createdDate": "2015-01-30T18:28:36.663+0000",
        "lineNumber": 1,
        "deleted": false
      }
    ]
  },
  "MetadataContainerId": "1dcg0000000Au7cAAC",
  "ErrorMsg": null,
  "IsCheckOnly": false,
  "MetadataContainerMemberId": null
}
```

**Comment by ccoleman2** [comment]
I'm also seeing this JSON output. It was an actual error, but a bit hard to read still.

**Comment by JenniferSimondsTableau** [comment]
You're lucky. My "problem" = null.

**Comment by ralphcallaway** [comment]
weird, these errors are kind of common since salesforce can be a bit unpredictable in their response formats (lack of documentation, unannounced changes with api versions), so parsing them is always a challenge

@JenniferSimondsTableau that error message isn't particular useful (line 1 and nothing else), but that's probably all sfdc is sending mm. you can check by doing the same action in the developer console and see what error they're giving you

in terms of a practical technique for bad compile errors, comment out the entire file, get it to save, then use a "binary search" to find the offending line by uncommenting out half the code (you'll need to ensure it's valid still). if there error occurs, comment out half of the remaining uncommented out code, otherwise, uncomment half of the commented out code. eventually you can narrow it down to a specific issue

ps - if you want more assistance with that, i'd head over to salesforce.stackexchange.com
