### ISSUE TITLE
Compiling not showing proper errors, and compiling more than I want to.

### ISSUE THREAD

**Issue by ScriptMonkey00** [joeferraro/MavensMate-SublimeText#562]
I did not see this bug listed so I hope I'm not repeating a report, but when I save a class with mavensmate that has an error (typo'ed object in SOQL, whatever) rather than the clean errors that I used to get, I get:

 Result: [OPERATION FAILED]: {"State": "Failed", "MetadataContainerMemberId": null, "IsCheckOnly": false, "DeployDetails": {"componentSuccesses": [], "componentFailures": [{"problemType": "Error", "fullName": "integratedAdvisingCenter", "fileName": "pages/integratedAdvisingCenter.page", "id": "0661a0000001tPtAAI", "lineNumber": null, "forPackageManifestFile": false, "requiresProductionTestRun": false, "created": false, "success": false, "problem": "MEANINGFULL ERROR MESSAGE HERE", "componentType": "ApexPage", "knownPackagingProblem": false, "columnNumber": null, "createdDate": "2015-04-19T13:40:28.842+0000", "changed": false, "deleted": false, "warning": false}], "allComponentMessages": [{"problemType": "Error", "fullName": "integratedAdvisingCenter", "fileName": "pages/integratedAdvisingCenter.page", "id": "0661a0000001tPtAAI", "lineNumber": null, "forPackageManifestFile": false, "requiresProductionTestRun": false, "created": false, "success": false, "problem": "Field $myStudents does not exist. Check spelling.", "componentType": "ApexPage", "knownPackagingProblem": false, "columnNumber": null, "createdDate": "2015-04-19T13:40:28.842+0000", "changed": false, "deleted": false, "warning": false}], "runTestResult": null}, "attributes": {"url": "/services/data/v31.0/tooling/sobjects/ContainerAsyncRequest/1dr1a000000LaqBAAS", "type": "ContainerAsyncRequest"}, "Id": "1dr1a000000LaqBAAS", "MetadataContainerId": "1dc1a0000000U6BAAU", "ErrorMsg": null}

In addition, the more frustrating part was that I was modifying two things, one in a class, one in a page.  Compiling the class obviously would break the page, but when I saved the class, I got an error very similiar to the one above, citing the .page file and the now-missing parameter even though I was saving (and I assume  compiling) only the class.  Just to resolve it, I deleted the entire .page file's contents, then saved it and it worked, then saved the class and it then told me the file in the org didn't match the local file.  I assume it's because it did save the file to the org, but didn't pull the new revision number because it didn't THINK it saved.

All in all it's been a confusing morning :)

**Comment by ScriptMonkey00** [comment]
Sorry, forgot to mention, I'm running SublimeText build 3083, and MavensMate plugin 4.0.4

**Comment by ralphcallaway** [comment]
@ScriptMonkey00 so that second part is kind of a "feature" of the tooling api. As you save stuff it's collecting everything into a "container", i.e. vf page and classes, and submitting them all together. The idea is you're working on vf page and you reference a method that doesn't exist yet in the controller and get a compile error, then you go to the controller add the method and save, at this point both are compiled and saved to salesforce instead of having to go back to the vf page and save.

The downside is this is confusing and you get errors for things you're not working on. When this happens you can just reset your metadata container and you'll start fresh. No need to delete things.

This doesn't apply to the metadata api.

Regarding the error message, salesforce is determined to provide a mystifying array of different formats for these errors, with minimal documentation, and then change them frequently. So this is a pretty common issue with mavens mate (and most of the other IDEs), posting these helps us figure out what the missing examples are.

**Comment by ScriptMonkey00** [comment]
Thank you so much for the assistance with this.  I actually didn't know about the Tooling API's batching aspect, and I appreciate the explanation.   Also, since I'm currently working with salesforce web callouts I completely understand what you mean about lack of documentation, since all SF offers is a list of parameters without any definitions and a vague example.

Best of luck with resolving this new error format, and if I can help with the resolution, just let me know.
