### ISSUE TITLE
Server not responding

### ISSUE THREAD

**Issue by rpbeam** [joeferraro/MavensMate-SublimeText#565]
The local MavensMate server did not respond properly. This likely means it is not running or it is malfunctioning. Try restarting your text editor and MavensMate.app.

we tried a clean install on Windows 7 and keep getting this error.

Thank you
Rodney

**Comment by rpbeam** [comment]
I have it working on my PC and tried setting up my friends exactly the same way.  We will try again in the morning

**Comment by ralphcallaway** [comment]
when are you getting the error? guessing this might have happened when you click create new project, enter details, and then hit submit?

in terms of troubleshooting there are a couple of things we need
- os and version (already got that)
- ST 3 version
- ST 3 mavens mate plugin version
- mavens mate version

logs are also help, see how to enable plugin logging

if you are having issues in one of the "UI" windows that open in your web browser, use your browsers developer tools to check the console for javascript errors

finally, you can also open the sublime text console and see if there is anything printer there that's useful (on windows I believe it's ctrl-` to open, but it might be different)

closing for now since there isn't any action we can take without troubleshooting details, re-open if this is still occurring and you can provide some additional diagnostic info
