### ISSUE TITLE
Apex Test Runner Filter + All toggle

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate-SublimeText#605]
Not sure if it is designed this way or not but I filtered my tests, using the search box, down to 5 test classes then clicked the "All" button expecting those 5 to be selected but turns out ALL test classes still get selected.

Would have assumed only the filtered tests would be checked.

**Comment by daeschwed** [comment]
Hi all
digging up ancient stuff, I know…
This issue seems to be resolved since ages: filtering and selecting works just as expected in regards to above posts.

@joeferraro Suggesting to close this issue.

for completeness sake, this post is based on the following setup:
OS X El Capitan v10.11.4
Sublime Text 3 Build 3103
MavensMate for Sublime Text v7.0.0-beta.1
MavensMate-app v0.0.11-beta1

Cheers
the swedish guy
