### ISSUE TITLE
Refresh from Server takes foreever

### ISSUE THREAD

**Issue by pjain11** [joeferraro/MavensMate-SublimeText#731]
When I do refresh from server, it stops with polling timeout error. increasing timeout but still takes 40-50 min. Our package.xml is huge. Why does the refresh routine takes so long, 40-50 min?

MM app v 0.0.11-Beta1
Osx v10.9.5

**Comment by joeferraro** [comment]
Hi @pjain11 please update your issue according to the contribution guidelines thanks!

**Comment by joeferraro** [comment]
Also, when submitting issues regarding performance, it's important to keep in mind that MavensMate is interfacing with Salesforce.com servers. Before submitting a performance-related issue, create a project that connects to an org that's different from the org where you're experiencing performance issues. If the issue does not persist in this new project, then the issue is Salesforce and not MavensMate.

**Comment by ize-h2t-io** [comment]
@joeferraro have you benchmarked MM with other "API clients" (e.g. aside.io) for similar operations across the same org? Same org, same operation (e.g. simply "save" a simple Apex or VF file), but different "API client"...

**Comment by joeferraro** [comment]
We always benchmark against the developer console

**Comment by ize-h2t-io** [comment]
Thanks @joeferraro. Do your tests imply performance parity between MM and standard developer console? Mine sure don't. I have observed wide performance variances between MM and other API clients (yes, including the standard developer console). How would you suggest I formalize these findings so they are actionable? What is the asynchronous polling frequency used by MM (e.g. save method)? Is this a setting that I can play with?
