### ISSUE TITLE
Is toggle_debug_panel available?

### ISSUE THREAD

**Issue by dkurylo** [joeferraro/MavensMate-SublimeText#739]
I wanted to add a key map for toggling the debug panel, but I did not find such command. Only open_debug_panel was found in the files. But MM clearly has an option for hiding it, since that behavior is configurable in the settings.
The question is: how do I add a key map for toggling the debug panel (i.e. open if closed and close if opened)?
Thanks!

**Comment by ralphcallaway** [comment]
are you referring to to the mavensmate console? i.e. where you see messages like this 
```
Operation: Cleaning Project
Timestamp: Tue, 27 Oct 2015 14:49:32
   Result: Success: Project cleaned successfully
```

if so it's got an existing key mapping for `super-shift-m`

**Comment by dkurylo** [comment]
@ralphcallaway Yes, I know about this. But it only opens the panel, it does not close that panel if it's already open. And the toggle works as checkbox - if closed - then open, if opened - then close.

**Comment by ralphcallaway** [comment]
@dkurylo makes sense, wiring `super-shift-m` to be a toggle instead of just open would be consistent with the st3 console (`ctrl-tilda` on macs) which does a toggle

fyi you can close the debug panel with `esc`, not sure how that's wired up, i get the impression it's a general sublime text feature as it also works to close the st3 console

**Comment by dkurylo** [comment]
@ralphcallaway yeah, I know about esc, but to close the console you have to place a focus on it, and then press esc, otherways it won't work for the console. And currently I'm working with it like this - rewired the key map to my preferred combination, and use it to open, and click to n the console and press esc to close. But it looks inconsistent, takes unnecessary steps to perform and is not too smart for an app like this.
So, is there any way make the console open and close like a toggle?

**Comment by ralphcallaway** [comment]
@dkurylo ahh, missed your line of question.

Looking at mavensmate.py, seeing a `HideDebugPanelCommand`, although it doesn't seem to work when i add a keymapping for `hide_debug_panel`

In terms of making it toggle, you'd want to add a new command to mavensmate.py and then put together a key mapping, unfortunately the day job is taking away all my focus, so that's about as far as I could get you at the moment

ps - not sure if it's mac specific, but `esc` closes the console for me regardless of where my focus is ...

**Comment by dkurylo** [comment]
@ralphcallaway Okay, thanks then, you're right, there are more valuable things to do with MM functionality, this is rather a not-so-annoying thing we can live with.
