### ISSUE TITLE
[MAVENTSMATE] failed to send community activity 

### ISSUE THREAD

**Issue by bonhomie** [joeferraro/MavensMate-SublimeText#755]
each time I compile, I notice that the text console it displays 

[MAVENTSMATE] failed to send community activity 

is there a way to switch this off?

**Comment by RachaelChipman82** [comment]
@joeferraro Hello, I am having the same issue as above and the compile times are extremely long, between 2-3 minutes, sometimes up to 10. I updated the MavensMate API version this morning and that's made no difference, I am assuming because I didn't need to update it. Then after that I tried another compile and the issue persists. My workspace is correctly set... What am I missing here?

Thanks!!!//rc 

Here is the log from my console:

DPI scale: 1.25
startup, version: 3114 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/rchipman/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/rchipman/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/rchipman/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "Package Control"]
pre session restore time: 0.183084
startup time: 0.229084
first paint time: 0.235084
first paint time: 0.236084
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin MavensMate.config
reloading plugin MavensMate.mavensmate
reloading plugin MavensMate.util
plugins loaded
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: checking for updated mm version
[MAVENSMATE]: mm is up to date (0.2.4), no further action needed
[MAVENSMATE] failed to send community activity
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: compile
[MAVENSMATE]: {'params': {'files': ['C:\\Users\\rchipman\\Documents\\MavensMate\\RPTraining Jan 2016\\src\\classes\\CloneOpportunityContExt.cls']}, 'context': <sublime.View object at 0x00000000042D19B0>}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\rchipman\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" -o compile -c SUBLIME_TEXT_3
[MAVENSMATE]: {"files": ["C:\\Users\\rchipman\\Documents\\MavensMate\\RPTraining Jan 2016\\src\\classes\\CloneOpportunityContExt.cls"], "project_name": "RPTraining Jan 2016", "workspace": "C:/Users/rchipman/Documents/MavensMate"}
[MAVENSMATE] failed to send community activity
[MAVENSMATE]: response from mm: {"checkOnly": false, "completedDate": "2016-06-27T14:18:37.000Z", "createdBy": "00500000007Em7P", "createdByName": "Rachael Chipman", "createdDate": "2016-06-27T14:17:07.000Z", "details": {"componentSuccesses": [{"changed": false, "componentType": "ApexClass", "created": false, "createdDate": "2016-06-27T14:17:27.000Z", "deleted": false, "fileName": "unpackaged/classes/CloneOpportunityContExt.cls", "fullName": "CloneOpportunityContExt", "id": "01p000000004UMhAAM", "success": true}, {"changed": true, "componentType": null, "created": false, "createdDate": "2016-06-27T14:17:28.000Z", "deleted": false, "fileName": "unpackaged/package.xml", "fullName": "package.xml", "success": true}], "runTestResult": {"numFailures": "0", "numTestsRun": "0", "totalTime": "0.0"}}, "done": true, "id": "0Af21000001UXxFCAW", "ignoreWarnings": false, "lastModifiedDate": "2016-06-27T14:18:37.000Z", "numberComponentErrors": "0", "numberComponentsDeployed": "1", "numberComponentsTotal": "1", "numberTestErrors": "0", "numberTestsCompleted": "0", "numberTestsTotal": "0", "rollbackOnError": true, "runTestsEnabled": false, "startDate": "2016-06-27T14:17:24.000Z", "status": "Succeeded", "success": true}


[MAVENSMATE]: HANDLING COMPILE!
[MAVENSMATE]: {'numberTestErrors': '0', 'completedDate': '2016-06-27T14:18:37.000Z', 'id': '0Af21000001UXxFCAW', 'rollbackOnError': True, 'numberComponentsDeployed': '1', 'ignoreWarnings': False, 'numberComponentsTotal': '1', 'done': True, 'createdByName': 'Rachael Chipman', 'numberTestsTotal': '0', 'lastModifiedDate': '2016-06-27T14:18:37.000Z', 'numberTestsCompleted': '0', 'runTestsEnabled': False, 'numberComponentErrors': '0', 'createdDate': '2016-06-27T14:17:07.000Z', 'startDate': '2016-06-27T14:17:24.000Z', 'status': 'Succeeded', 'success': True, 'details': {'runTestResult': {'totalTime': '0.0', 'numFailures': '0', 'numTestsRun': '0'}, 'componentSuccesses': [{'deleted': False, 'changed': False, 'fullName': 'CloneOpportunityContExt', 'id': '01p000000004UMhAAM', 'created': False, 'fileName': 'unpackaged/classes/CloneOpportunityContExt.cls', 'componentType': 'ApexClass', 'createdDate': '2016-06-27T14:17:27.000Z', 'success': True}, {'deleted': False, 'changed': True, 'fullName': 'package.xml', 'created': False, 'fileName': 'unpackaged/package.xml', 'componentType': None, 'createdDate': '2016-06-27T14:17:28.000Z', 'success': True}]}, 'checkOnly': False, 'createdBy': '00500000007Em7P'}
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: index_apex
[MAVENSMATE]: {'params': {'files': ['C:\\Users\\rchipman\\Documents\\MavensMate\\RPTraining Jan 2016\\src\\classes\\CloneOpportunityContExt.cls']}}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\rchipman\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" -o index_apex -c SUBLIME_TEXT_3
[MAVENSMATE]: {"files": ["C:\\Users\\rchipman\\Documents\\MavensMate\\RPTraining Jan 2016\\src\\classes\\CloneOpportunityContExt.cls"], "project_name": "RPTraining Jan 2016", "workspace": "C:/Users/rchipman/Documents/MavensMate"}
[MAVENSMATE] failed to send community activity
[MAVENSMATE]: response from mm: {


    "body": "Apex symbols indexed successfully", 


    "body_type": "text", 


    "success": true, 


    "time": "4.913999795913696"


}
