### ISSUE TITLE
MavensMate does not use TLS 1.1 to connect to Salesforce

### ISSUE THREAD

**Issue by beamso** [joeferraro/MavensMate-SublimeText#769]
A critical update called 'Require TLS 1.1 or higher for HTTPS connections' appeared in my Salesforce developer org.  After activating the critical update, I was unable to save files to my Salesforce org.

The error displayed was

> Server raised fault: 'UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.'

I have deactivated the critical update for now.

**Comment by ralphcallaway** [comment]
@beamso which version are you using?

**Comment by jordanbaucke** [comment]
@beamso getting this issue as well. 

MavensMate App: **v0.0.10**
SublimeText Plugin: **MavensMate for Sublime Text v6.0.0**

**Comment by beamso** [comment]
MavensMate for Sublime Text v6.0.0

**Comment by beamso** [comment]
I've done some further investigation.  I can run some commands using the MavensMate node.js project against an org with the critical update turned on, i.e. executing SOQL, indexing metadata, compiling projects, but it's only when I attempt to use the MavensMateWindowServer that I get complaints about the TLS version.

**Comment by joeferraro** [comment]
@beamso v7 of the plugin does not use the window server --> https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas

**Comment by beamso** [comment]
That worked.  I'm taking a guess that it's `mm` executable packaged inside the window server executable that is opening the connection to Salesforce and it needs to be updated to support a TLS 1.1 connection.

**Comment by scamozzi** [comment]
Having the same issue.  When I activate the update in a sandbox that disables TLS I get the error: "Server raised fault: 'UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.'"

MavensMate for Sublime Text v6.0.0 on OS X Yosemite 10.10.5. MavensMate v0.0.10.

**Comment by smeeGit** [comment]
Same issue - I've re-enabled TLS 1.0 for now.  The critical update that disables TLS 1.0 auto updates on 6/25/2016 - I'm hoping for an update prior to then :)

**Comment by zokier07** [comment]
Same issue but just on MavensMate for Sublime on OS X Yosemite.
Works fine on MavensMate for Windows.

**Comment by hemmeter** [comment]
Happening to me too once the Critical Update in salesforce is activated. Error is...

`Server raised fault: 'UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.'
`

MavensMate for Sublime Text v6.0.0 on El Capitan.

**Comment by joeferraro** [comment]
Hey guys, so it doesn't look particularly straightforward to support TLS 1.1 in the Python-based `mm` tool. In the meantime, we're recommending folks use the node-based betas: https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas

**Comment by hemmeter** [comment]
Upgraded to version 7 betas did the trick

**Comment by Jeremywhiteley** [comment]
The upgrade instructions to version 7 are not clear and don't work.   Why can't you provide clear instructions on how to solve this issue?

**Comment by soaksash** [comment]
This is still a free package. Shouldnt everyone be nicer to one another and contribute positively.

**Comment by sameersheikh** [comment]
@Jeremywhiteley - I have found how to do it ( I have done on my Mac Machine, so if you are on windows I believe its pretty much the same too)

When you get the error for TLS, the first thing you need to do is: 

**Step 1:**
Go to Mavensmate tab on sublime Text --> Settings --> User Plugin Settings. Open it in sublime

On the file set the value true as shown in code below from the same file By default your machine will install the Mavensmate-app on the below default directories(I assume):

//set to true if you would like to automatically start MavensMate-app when Sublime Text opens
	**"mm_start_mavensmate_app" : **true**,

	// set to full path of MavensMate-app (MavensMate.app on OSX, MavensMate.exe on Windows, etc.)
	"mm_mavensmate_app_location" : {
		"osx": "/Applications/MavensMate.app",
		"windows": "C:\\Program Files\\MavensMate.exe",
		"linux": ""
	},**


**Step 2:**
Download and Install Mavesmate-app from the url. Choose according to your operating system:
- https://github.com/joeferraro/mavensmate-app/releases 

**Step 3:**
Once Installed, open the MavensMate app from the installed apps and go to the app Settings by click right top bars. Set your Workspace (Copy it exactly and change your name whereever you have installed it) :  ["/Users/Jeremy.xyz/workspace"]

Once entered, click on the app anywhere to make sure it has saved the settings. Restart your sublime. 

Please make a note that the Mavensmate app needs to be running along side your sublime in order to work.

Let me know if that worked for you as it did worked for me :)

**Comment by chalemic** [comment]
@sameersheikh - thank you for the detailed instructions. Unfortunately, I'm still getting the TLS error.

Config: MavensMate for Sublime Text v6.0.3 on a Mac
* I added mm_start_mavensmate_app and mm_mavensmate_app_location to my user settings and restarted Sublime. 
* I installed v0.0.10 of MavensMate.app and set the workspace. 
* I've tried starting Sublime with MavensMate.app already running and without it running to no avail.

I also tried the directions at https://github.com/joeferraro/MavensMate-SublimeText/blob/master/messages/rollback.md to enable the pre-release but then the MavensMate plugin wouldn't load at all when I restarted Sublime. I did not try the pre-release channel with the app, though.

**Comment by vimarshkarbhari-okta** [comment]
@sameersheikh I tried all the steps and I am still getting the same error.

**Comment by iubkud** [comment]
Thanks so much @sameersheikh this worked for me.

**Comment by sameersheikh** [comment]
@vimarshkarbhari-okta / @chalemic 

When you installed MavensMate-App, was the installation location exactly as mentioned below? or you installed at different path and then changed the settings below to route it to right directory?

// set to full path of MavensMate-app (MavensMate.app on OSX, MavensMate.exe on Windows, etc.)
	"mm_mavensmate_app_location" : {
		"osx": "/Applications/MavensMate.app",
		"windows": "C:\\Program Files\\MavensMate.exe",
		"linux": ""
	},

@chalemic - Did you configured the pre-release settings in sublime-settings as provided in the link?

**Comment by vimarshkarbhari-okta** [comment]
@sameersheikh -
I installed and then moved the app to the right directory.

**Comment by chalemic** [comment]
@ sameersheikh - I've got it mostly working. After switching the package setting to the pre-release channel I had to run "Package Control: Install Package".

Now I just have to get syntax highlighting and autocomplete working again.

**Comment by vimarshkarbhari-okta** [comment]
@sameersheikh - Anything you suggest I should do to fix this?

**Comment by srajagopalan1712** [comment]
I upgraded to Sublime 7 and installed the MavensMate.app. Changed the settings as said to include right location and to start app when sublime starts. I set the right mm_workspace in the settings. When I try to save a file I now get this

 Result: [ERROR]: Request to the local MavensMate server failed. Error initializing project: MavensMate could not find project with the id: XAF7R3OEUE0G763KBOLO8JZPGEG9XQC3. This is likely because you are trying to open a project that does not reside in a valid mm_workspace. Please go to MavensMate-app global settings and ensure this project is located in a valid mm_workspace.

Here is my value for workspace
[
  "/Users/saradha/MM/MyProjectHome"
]

Let me know if I am doing anything wrong. I also restarted sublime after all changes and same error later too.

**Comment by sameersheikh** [comment]
@srajagopalan1712 - Looks like Upgrade is done and its just the path issue for workspace. Does the project appears after setting the path in your MavensMate-app? try opening a project from the app and see if you can see it. I had the same error too. All I did was to make sure the workspace path was correct and I was missing " ". 

Are you using Mac or Windows?

**Comment by vimarshkarbhari-okta** [comment]
@sameersheikh - I was able to make it work using : https://www.xgeek.net/salesforce/to-fix-error-require-tls-1-1-for-https-connections-of-mavensmate-v6-0/
Thank you for your help

**Comment by smcmickle** [comment]
@Jeremywhiteley 

Hmm, I followed the instructions and they worked perfectly for me! 

I simply added Mavensmate to the prerelease section in the JSON file for packages, then I ran the install updates command. Too easy 👍

**Comment by srajagopalan1712** [comment]
I am using mac. I made sure many times that my workspace is right, ["...."]. I already have my sublime and Mavens xx.sublime-project which opens in Sublime when I open it. Also does the new MavensMate app.  I set the workspace here and while saving a file in my existing project, I see this error. 

I do not see the project when I open in .app

**Comment by srajagopalan1712** [comment]
I got it to work. I had to change the workspace from this  "/Users/saradha/MM/MyProjectHome" to "/Users/saradha/MM" where the project lived. Thanks again!!

**Comment by gongsy945** [comment]
@beamso getting this issue as well.
Sublime Text 3
MavensMate for Sublime Text v6.0.3

**Comment by yenkey** [comment]
Got the same issue. Resolved after upgrading to mavenmate 7 using package control--> upgrade-->mavenmate 7

Followed the instructions from the below links before upgrading.
https://github.com/joeferraro/MavensMate-SublimeText
https://www.xgeek.net/salesforce/to-fix-error-require-tls-1-1-for-https-connections-of-mavensmate-v6-0/
