### ISSUE TITLE
Unrecognized package.xml metadata type: AssignmentRule

### ISSUE THREAD

**Issue by yperez** [joeferraro/MavensMate-SublimeText#822]
In Version 7.0.0-beta.3

[MAVENSMATE]: Calling mavensmate adapter
[MAVENSMATE]: OPERATION: clean-project
[MAVENSMATE]: {'context': <MavensMate.mavensmate.CleanProjectCommand object at 0x109b0d690>}
[MAVENSMATE]: http://localhost:56248/execute?command=clean-project&async=1&pid=f41115d0-47b2-11e6-a529-7b21f1f0dc2d
reloading /Users/yperez/Documents/workspace/Hologic Dev2/src/package.xml
[MAVENSMATE]: urllib.error.HTTPError
[MAVENSMATE]: Error initializing project: Unrecognized package.xml metadata type: AssignmentRule
[MAVENSMATE]: Error initializing project: Unrecognized package.xml metadata type: AssignmentRule
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'error': 'Request to the local MavensMate server failed. Error initializing project: Unrecognized package.xml metadata type: AssignmentRule'}

**Comment by mginou** [comment]
Any indication of why this issue was closed or the workaround/fix?

I am getting this, but AssignmentRule is definitely supported in all recent API versions. Furthermore, I actually don't have an AssignmentRule section (AssignmentRules is in the package); and the error still pops up when I remove it.

I also tried purging some the files in the .config control folder in case it was a caching issue, but that hasn't helped either.

**Comment by bjanderson70** [comment]
I corrected the issue by:
Using the more plural form( as MM did not recognize the singular form):
instead of:
<types>
    <members>Case.my case rule</members>
    <name>AssignmentRule</name>
</types>

changed ....

<types>
    <members>Case</members>
    <name>AssignmentRules</name>
</types>
