### ISSUE TITLE
Result: [ERROR]: result.resolve is not a function

### ISSUE THREAD

**Issue by sagarsindhi** [joeferraro/MavensMate-SublimeText#854]
Error while saving any record from sublime using mavensmate

**Comment by elvissipa** [comment]
I am getting the same error when trying to open a new project, any suggestions ? Result: [ERROR]: result.resolve is not a function

**Comment by elvissipa** [comment]
Found an answer:  In the sublime text Mavens-Mate settings make sure that both your path to mavensmate AND your path to sublime text is correct. Then under Mavensmate Global settings (the gear), go down to The full path of your Sublime Text executable (Sublime Text users only). and change the path to correct location. Make sure with windows, you're using "\\" instead of a "\" in your path. Restart your PC and start mavensmate, then sublime.

https://github.com/joeferraro/MavensMate/issues/788

**Comment by nnimran** [comment]
I am facing same issue.
